### ISSUE TITLE
Pharaoh abuse

### ISSUE THREAD

**Issue by Creyox** [TTT-2/ttt2-role_pha#5]
Mit dem Pharaoh ist es möglich einen Abuse auszunutzen:

Man platziert das Ankh und entfernt es direkt wieder. Dadurch wird ein Traitor zum Graverobber und hat keinen Zugriff auf den T-Shop mehr, kann aber kein Ankh übernehmen. Vielleicht machst du das Ankh einfach nicht mehr aufnehmbar, das wäre die einfachste Lösung.

**Comment by LunexKun** [comment]
Dafür gibt es soweit ich weiß eine Convar.
Und, wenn du dein ankh nichtmehr hinstellst, hast du ja auch nichts vom ankh. 
Und, du musst immer bedenken, dass der T dir auch einfach so ne deagel schelle geben kann ;) Er hat ja eh den ersten schuß :p

**Comment by LunexKun** [comment]
*falls es keine CVAR dafür gibt, stimme ich dir zu, da sollte man eine hinzufügen*

**Comment by Creyox** [comment]
Stimmt sorry, habs grad nochmal nachgeguckt. War irgendwie davon ausgegangen, dass es keine gibt, da das standardmäßig so ist
